### ISSUE TITLE
t.throws failures mislead

### ISSUE THREAD

**Issue by mixmix** [tbeseda/tap-spek#29]
**Describe the issue**
I'm using `t.throws` and tap-arc is giving me misleading + unhelpful output when such an assertion fails

**Steps to reproduce**

```js
  t.throws(
    () => {
      throw new Error('no good error')
    },
    /bad error/
  )
```
See an failed test which says "expected not to throw"

**Expected behavior**
Should:
- assert that a throw was expected + received
- inform that the Error thrown did not match expectation

**Screenshots**
![image](https://user-images.githubusercontent.com/2665886/177434124-2e41f369-c373-4ed7-bb7b-af6963379b4b.png)

**Desktop**
Please complete the following information (if appropriate):
 - Version : tap-arc@0.3.4
 - Node: v14.19.0

**Comment by mixmix** [comment]
```js
  t.throws(
    () => {
      throw new Error('no good error')
    },
    /bad error/,
    'failing case'
  )
```
Is more clear:

![image](https://user-images.githubusercontent.com/2665886/177434509-62ab110d-28e4-4a9a-8e52-97ed019050b8.png)

But it still says "Expected to not throw", which is wrong

**Comment by tbeseda** [comment]
hey @mixmix thanks for the report and the reproduction case!
I rarely use that expectation match with throws, so I hadn't accounted for the case where there is an `actual` that is an Error but that it doesn't match `expected`.
I've got a new handler cover that case and a new set of tests around the "throws" operator; it prints like:
```
    ✔ passing match case
    ✖ 4) failing no match case
      Expected '/bad error/' to match "{ [Error: no good error] message: 'no good error' }"
      At: Test.<anonymous> (/test/create-throws-tap.js:16:5)
```

I'm resisting a refactor for the moment, but it is at the point where the tree of cases is hard to reason about.
I'll get a new version out soon to cover this and then think on patterns for a wide branching if-statement :)

**Comment by mixmix** [comment]
Awesome, thank you so much!

I've been recommending this module and transitioning a bunch of modules to
it.

Keen to continue to try support as best I can. Give me feedback if issues
could be better, or if you think a fix would be easy and you'd welcome PRs.

Unrelated: would be nice to bump to semver 1.0.0 - this has nicer update
properties I think (semver <1 can behave weird as considered alpha/beta?)
