### ISSUE TITLE
Request to add extra colour syntax highlighting

### ISSUE THREAD

**Issue by darcyrush** [tbeseda/tap-spek#31]
**Is your feature request related to a problem?**
When diffing any long strings (complex nested objects that are output as a string due to size or escape characters, base64 output, stringified business data, etc, etc), it is very difficult to see any difference. Expected is completely in red while received is completely in green.
```html
<span style="color:red"  >- { some: { example: { object: { property: '123456' } } } }</span>
<span style="color:green">+ { some: { example: { object: { property: '123457' } } } }</span>
```
_(Excuse the html markup - not sure how to explain without)_

**Describe the solution you'd like**
A new flag would be nice for an extra type of colouring.  Something like `--color-differences`. All output is without colour, except for the character differences.
```html
- { some: { example: { object: { property: '12345<span style="color:red"  >6</span>' } } } }
+ { some: { example: { object: { property: '12345<span style="color:green">7</span>' } } } }
```
The important detail is that both the expected and received lines are output. In the case that characters are missing or extraneous, only the missing / added characters are coloured, similar to the current default behaviour.
```html
- { some: { example: { object: { property: '123456' } } } }
+ { some: { example: { object: { property: '123456<span style="color:green">7</span>' } } } }
```

**Describe alternatives you've considered**
Using console background colours with the default behaviour, but that might be difficult due to contrast, limited support etc.

**Additional context or notes**
I have read the closed issues in relation to this, but I think the issues and solutions are subtly different.

I have not seen other tap reporters implement this.

For extra polish, the `+` and `-` line prefixes could be coloured to make reading even easier.
```html
<span style="color:red"  >-</span> { some: { example: { object: { property: '12345<span style="color:red"  >6</span>' } } } }
<span style="color:green">+</span> { some: { example: { object: { property: '12345<span style="color:green">7</span>' } } } }
```

**Comment by Munawwar** [comment]
How about this? https://github.com/architect/tap-arc/compare/main...Munawwar:tap-arc:main

Before:
![before](https://github.com/user-attachments/assets/bd713a35-c3c6-421a-9766-15de7d28b499)

After:
![after](https://github.com/user-attachments/assets/952f8088-9c2e-4a66-8b5b-235798307a49)
